backend/controllers/AuthController.php
<?php

namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use common\auth\Identity;
use backend\managers\AuthManager;
use backend\models\collections\LoginCollection;
use yii\filters\AccessControl;

/**
 * Class AuthController
 * @package backend\controllers
 */
class AuthController extends Controller
{
    public $layout = 'login';

    private $_manager;

    public function __construct($id, $module, AuthManager $manager, array $config = [])
    {
        parent::__construct($id, $module, $config);

        $this->_manager = $manager;
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (Yii::$app->user->can('admin'))
            return $this->goHome();

        $collection = new LoginCollection();

        if ($collection->load(Yii::$app->request->post()) && $collection->validate()) {
            try {
                $user = $this->_manager->auth($collection);
                Yii::$app->user->login($user, $collection->rememberMe ? 3600 * 24 * 30 : 0);

                return $this->goBack();
            } catch (\DomainException $e) {
                Yii::$app->errorHandler->logException($e);
                Yii::$app->session->setFlash('error', $e->getMessage());
            }
        }

        $this->view->title = Yii::t('app', 'Authorization');

        return $this->render('login', [
            'model' => $collection,
        ]);
    }

    /**
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return array
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }
}

backend/views/layouts/login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/**
 * @var $this    \yii\web\View
 * @var $content string
 */
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login">
<?php $this->beginBody() ?>

<div class="container wrapper">
    <div id="login-wrapper" class="row">
        <div class="col-lg-4 col-md-5 col-sm-6 col-11 center-box"><?= $content ?></div>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use kartik\icons\Icon;
use yii\widgets\Breadcrumbs;
use backend\widgets\MainMenu;
use backend\widgets\Alert;

Icon::map($this);

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrapper">
    <header class="navbar navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="/" class="navbar-brand"><strong><?= Yii::$app->name; ?></strong> admin</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item"><a
                            href="<?= Yii::$app->params['frontendHostInfo']; ?>"><?= Icon::show('desktop', ['class' => 'icon']); ?>
                        Перейти на сайт</a></li>
                <li class="nav-item"><a href="#"><?= Icon::show('user', ['class' => 'icon']); ?>Сергей Димитриев</a>
                </li>
                <li class="nav-item"><?= Html::a(Icon::show('power-off'), ['/auth/logout'], ['data-method' => 'post', 'title' => Yii::t('app', 'Logout')]) ?></li>
            </ul>
        </div>
    </header>
    <aside class="sidebar">
        <?= MainMenu::widget([
            'options'         => [
                'class' => 'sidebar-menu',
            ],
            'submenuTemplate' => '<ul class="treeview-menu">{items}</ul>',
        ]); ?>
    </aside>
    <section class="content">
        <div class="clearfix" style="height: 100%">
            <div class="main">
                <div class="content-header">
                    <h1><?= $this->title; ?></h1>
                    <?= Breadcrumbs::widget([
                        'options'  => [
                            'class' => 'breadcrumb flat',
                        ],
                        'homeLink' => [
                            'label' => Yii::t('app', 'Dashboard'),
                            'url'   => '/',
                        ],
                        'links'    => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                    ]) ?>
                </div>
                <div class="content-body container-fluid">
                    <?= Alert::widget(['options' => ['class' => 'flat']]) ?>
                    <?= $content; ?>
                </div>
            </div>
        </div>
    </section>
    <footer></footer>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>